### ISSUE TITLE
destroy runs like apply

### ISSUE THREAD

**Issue by christoappleton** [coreos/terraform-aws-tectonic#14]
The deploy kicked off fine, great work!  This is a me issue but thought I would confirm, using v0.11.1 when I try to destroy it behaves like the apply, prompting for vars if not declared and refreshing state.  Used a local tfstate and seems to be reflective of the env, is it possible I have an issue there or with some variable declarations?  I should be able to destroy this as it is yes?

**Comment by squat** [comment]
This is expected behavior. Terraform will re-construct the dependency graph before deletions and to do that it needs all information pertaining to the infrastructure.
