### ISSUE TITLE
Customize the deployment

### ISSUE THREAD

**Issue by ghost** [coreos/terraform-aws-tectonic#21]
what file do i modify to get this working the file in dir example/kubernetes or the variable.tf in the top level directory, documentation was not clear. This will be a stock build without Tectonic features.

**Comment by ghost** [comment]
why am i getting this error:

Warning: output "etcd_sg_id": must use splat syntax to access aws_security_group.etcd attribute "id", because it has "count" set; use aws_security_group.etcd.*.id to obtain a list of the attributes across all instances



Warning: output "aws_api_external_dns_name": must use splat syntax to access aws_elb.api_external attribute "dns_name", because it has "count" set; use aws_elb.api_external.*.dns_name to obtain a list of the attributes across all instances



Warning: output "aws_elb_api_external_zone_id": must use splat syntax to access aws_elb.api_external attribute "zone_id", because it has "count" set; use aws_elb.api_external.*.zone_id to obtain a list of the attributes across all instances



Warning: output "aws_api_internal_dns_name": must use splat syntax to access aws_elb.api_internal attribute "dns_name", because it has "count" set; use aws_elb.api_internal.*.dns_name to obtain a list of the attributes across all instances



Warning: output "aws_elb_api_internal_zone_id": must use splat syntax to access aws_elb.api_internal attribute "zone_id", because it has "count" set; use aws_elb.api_internal.*.zone_id to obtain a list of the attributes across all instances



Warning: output "etcd_sg_id": must use splat syntax to access aws_security_group.etcd attribute "id", because it has "count" set; use aws_security_group.etcd.*.id to obtain a list of the attributes across all instances



Warning: output "aws_api_external_dns_name": must use splat syntax to access aws_elb.api_external attribute "dns_name", because it has "count" set; use aws_elb.api_external.*.dns_name to obtain a list of the attributes across all instances



Warning: output "aws_elb_api_external_zone_id": must use splat syntax to access aws_elb.api_external attribute "zone_id", because it has "count" set; use aws_elb.api_external.*.zone_id to obtain a list of the attributes across all instances



Warning: output "aws_api_internal_dns_name": must use splat syntax to access aws_elb.api_internal attribute "dns_name", because it has "count" set; use aws_elb.api_internal.*.dns_name to obtain a list of the attributes across all instances



Warning: output "aws_elb_api_internal_zone_id": must use splat syntax to access aws_elb.api_internal attribute "zone_id", because it has "count" set; use aws_elb.api_internal.*.zone_id to obtain a list of the attributes across all instances



Error: module.tectonic.template_dir.tectonic: 1 error(s) occurred:

* module.tectonic.template_dir.tectonic: file: open : no such file or directory in:

${base64encode(file(var.license_path))}

**Comment by ghost** [comment]
is it bpoth config.tf and variable.tf that need to be modified?

i added my zone ID to variable.tf but getting this error

Error: Error refreshing state: 1 error(s) occurred:


* module.dns.data.aws_route53_zone.tectonic: 1 error(s) occurred:

* module.dns.data.aws_route53_zone.tectonic: data.aws_route53_zone.tectonic: no matching Route53Zone found

**Comment by squat** [comment]
There are a few ways to give values to the declared variables. The most common way is to create a `terraform.tfvars` file [0] that specifies the values for the variables that are required or that you want to override.

Neither config.tf nor variables.tf should be modified; both of these files are necessary configuration files that declare the variables that are used in the module as well as provide sane defaults.

[0] 
https://www.terraform.io/intro/getting-started/variables.html#assigning-variables
